### ISSUE TITLE
Add unit tests

### ISSUE THREAD

**Issue by KillWolfVlad** [Byndyusoft/nest-http-client#11]

**Comment by litichevskiydv** [comment]
Ждем результатов ревью к следующему стендапу

**Comment by litichevskiydv** [comment]
@KillWolfVlad посмотрит PR после 21.11

**Comment by litichevskiydv** [comment]
Ждем ревью

**Comment by litichevskiydv** [comment]
Вернемся к теме в конце февраля

**Comment by litichevskiydv** [comment]
Ждем ревтю PR'а, который скинет Влад

**Comment by litichevskiydv** [comment]
Ревьювим PR на следующей сходке нодеров

**Comment by litichevskiydv** [comment]
Обсуждаем замечания на сходке нодеров, когда Влад выйдет из отпуска

**Comment by litichevskiydv** [comment]
Ждем правки к сентябрю
